### ISSUE TITLE
Validating Users

### ISSUE THREAD

**Issue by akaplo** [molecular-playground/frontend#1]
Part of creating a user involves sending an email to "validate" said user.

The email will contain a link with an alphanumeric string that we will use to determine which user to validate.  The scope of this issue is for the frontend to create a route that this link will send users to.  It might say something along the lines of `"You've been validated! Redirecting to your new homepage."`

The key here is that the frontend will make a request via the HTTP verb `patch` to the `/validate` path in the [ms-users microservice](https://github.com/Molecular-Playground/ms-users/blob/master/routes/users.js#L66) before redirecting them to their homepage.

**Comment by GaryPWhite** [comment]
[PATCH](http://restcookbook.com/HTTP%20Methods/patch/) on "validate" seems like the wrong verb. As the link says, it's for updating information, not creating new objects. It is also [isn't supported by all browsers](http://api.jquery.com/jQuery.ajax/) Perhaps a separate route should be created to register a user. POST seems more appropriate for a "new user". 

Unless, The scope of this issue is that we need a page from the e-mail sent, which I would agree with. Although, I would still advocate for PUT, not PATCH for browser support.

**Comment by stanleyrya** [comment]
This is actually the third time we had this conversation haha. This is however the first time anyone brought up that it isn't supported by all browsers. I also suggest we switch it then.

**Comment by stanleyrya** [comment]
As referenced up above, PATCH has been moved to PUT so we can move forward.

**Comment by GaryPWhite** [comment]
woops, forgot to mark this as CLOSED.
